#!/usr/bin/env bash
# Determine the path to load libjvm.so from, either relative to the location of
# the java binary or to $JAVA_HOME, if set.
JAVA_BIN=$(readlink -f "$(which java)")
JAVA_HOME=${JAVA_HOME:-${JAVA_BIN%/bin/java}}
# The location of libjvm.so relative to the JDK differs between JDK <= 8 and 9+.
JVM_LD_LIBRARY_PATH="$JAVA_HOME/lib/server:$JAVA_HOME/lib/amd64/server"

LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$JVM_LD_LIBRARY_PATH \
"$(dirname "$0")/jazzer_driver" "$@"

