// Copyright 2026 Code Intelligence GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Implements PC symbolization for Jazzer's synthetic (fake) coverage PCs.
//
// Java bytecode instrumentation assigns each control-flow edge a globally
// unique integer PC.  This module maps those PCs back to Java source
// locations (file, method, line) so that libFuzzer's -print_pcs,
// -print_funcs, and -print_coverage flags produce human-readable output.

#include "synthetic_symbolizer.h"

#include <jni.h>

#include <atomic>
#include <cstdio>
#include <string>
#include <unordered_map>
#include <vector>

#include "counters_tracker.h"

// The JNI header is auto-generated by rules_jni from
// SourceLocationRegistry.java.
#include "com_code_intelligence_jazzer_runtime_SourceLocationRegistry.h"

// ── Async-signal-safe spinlock ───────────────────────────────────
//
// std::mutex is NOT async-signal-safe. If a crash/timeout signal fires
// while registerLocations holds a std::mutex, the signal handler would
// deadlock trying to symbolize the crash.  We use std::atomic_flag with
// a bounded spin so the reader (SymbolizePC) either acquires the lock
// quickly or gives up and returns "<unknown>".

namespace {

class SpinLock {
 public:
  // Used by writers (registerLocations). Spins until acquired.
  void lock() {
    while (flag_.test_and_set(std::memory_order_acquire)) {
#if defined(__x86_64__) || defined(__i386__)
      __builtin_ia32_pause();
#elif defined(__aarch64__) || defined(__arm__)
      asm volatile("yield");
#endif
    }
  }

  // Used by readers (SymbolizePC, possibly from signal handlers).
  // Spins for at most `max_spins` iterations, then gives up.
  bool try_lock(int max_spins = 4096) {
    for (int i = 0; i < max_spins; ++i) {
      if (!flag_.test_and_set(std::memory_order_acquire)) {
        return true;
      }
    }
    return false;
  }

  void unlock() { flag_.clear(std::memory_order_release); }

 private:
  std::atomic_flag flag_ = ATOMIC_FLAG_INIT;
};

// ── Data structures ──────────────────────────────────────────────

constexpr uint32_t kNoLocation = UINT32_MAX;

struct PCLocation {
  uint32_t file_idx = kNoLocation;
  uint32_t func_idx = kNoLocation;
  uint32_t line = 0;
};

SpinLock gLock;

// O(1) index by string value; O(1) lookup by index during symbolization.
std::vector<std::string> gStringTable;
std::unordered_map<std::string, uint32_t> gStringLookup;

// Indexed by edge ID. file_idx == kNoLocation means "no data registered".
// line == 0 simply means "no debug info" but file/method are still valid.
std::vector<PCLocation> gLocations;

uint32_t InternString(const std::string &s) {
  auto it = gStringLookup.find(s);
  if (it != gStringLookup.end()) return it->second;
  auto idx = static_cast<uint32_t>(gStringTable.size());
  gStringTable.push_back(s);
  gStringLookup[s] = idx;
  return idx;
}

// Undo libFuzzer's GetNextInstructionPc before lookup.
uintptr_t ToPCTablePC(uintptr_t symbolizer_pc) {
#if defined(__aarch64__) || defined(__arm__)
  return symbolizer_pc - 4;
#elif defined(__mips__)
  return symbolizer_pc - 8;
#elif defined(__powerpc__) || defined(__sparc__)
  return symbolizer_pc - 4;
#else
  return symbolizer_pc - 1;
#endif
}

}  // namespace

// ── JNI: register source locations for a batch of edges ──────────

[[maybe_unused]] void
Java_com_code_1intelligence_jazzer_runtime_SourceLocationRegistry_registerLocations(
    JNIEnv *env, jclass, jstring source_file_jni, jobjectArray method_names_jni,
    jint first_edge_id, jintArray edge_data_jni) {
  if (!source_file_jni || !method_names_jni || !edge_data_jni) return;
  if (first_edge_id < 0) return;

  // Extract Java strings before acquiring the lock.
  const char *source_file_c = env->GetStringUTFChars(source_file_jni, nullptr);
  std::string source_file(source_file_c);
  env->ReleaseStringUTFChars(source_file_jni, source_file_c);

  jsize num_methods = env->GetArrayLength(method_names_jni);
  std::vector<std::string> method_names(num_methods);
  for (jsize i = 0; i < num_methods; ++i) {
    auto name_jni =
        static_cast<jstring>(env->GetObjectArrayElement(method_names_jni, i));
    const char *name_c = env->GetStringUTFChars(name_jni, nullptr);
    method_names[i] = name_c;
    env->ReleaseStringUTFChars(name_jni, name_c);
    env->DeleteLocalRef(name_jni);
  }

  jsize data_len = env->GetArrayLength(edge_data_jni);
  if (data_len < 2) return;
  std::vector<jint> raw_data(data_len);
  env->GetIntArrayRegion(edge_data_jni, 0, data_len, raw_data.data());

  auto base = static_cast<std::size_t>(first_edge_id);
  std::size_t num_edges = static_cast<std::size_t>(data_len) / 2;

  // Collect function-entry edge IDs so we can update PC flags
  // outside the spinlock (avoids nested lock: spinlock -> mutex).
  std::vector<std::size_t> func_entry_edges;

  gLock.lock();

  uint32_t file_idx = InternString(source_file);

  std::vector<uint32_t> func_indices(num_methods);
  for (jsize i = 0; i < num_methods; ++i) {
    func_indices[i] = InternString(method_names[i]);
  }

  if (base + num_edges > gLocations.size()) {
    gLocations.resize(base + num_edges);
  }

  for (std::size_t i = 0; i < num_edges; ++i) {
    auto packed_line = static_cast<uint32_t>(raw_data[2 * i]);
    auto method_idx_local = static_cast<uint32_t>(raw_data[2 * i + 1]);

    bool is_func_entry = (packed_line & 0x80000000u) != 0;
    uint32_t line = packed_line & 0x7FFFFFFFu;

    uint32_t func_idx = method_idx_local < func_indices.size()
                            ? func_indices[method_idx_local]
                            : 0;
    gLocations[base + i] = {file_idx, func_idx, line};

    if (is_func_entry) {
      func_entry_edges.push_back(base + i);
    }
  }

  gLock.unlock();

  // Mark function-entry PC flags outside the spinlock.
  for (auto edge_id : func_entry_edges) {
    jazzer::CountersTracker::SetCoveragePCFlags(edge_id, 1);
  }
}

// ── SymbolizePC ──────────────────────────────────────────────────

namespace jazzer {

void SymbolizePC(uintptr_t pc, const char *fmt, char *out_buf,
                 size_t out_buf_size) {
  if (out_buf_size == 0) return;

  auto orig_pc = ToPCTablePC(pc);

  // Copy strings into stack-locals while the lock is held so we
  // don't use dangling c_str() pointers after unlock.
  char file_buf[512] = "<unknown>";
  char func_buf[256] = "<unknown>";
  uint32_t line = 0;

  // Bounded try-lock: bail out if we can't acquire (crash handler safety).
  bool locked = gLock.try_lock();
  if (locked) {
    if (orig_pc < gLocations.size() &&
        gLocations[orig_pc].file_idx != kNoLocation) {
      const auto &loc = gLocations[orig_pc];
      snprintf(file_buf, sizeof(file_buf), "%s",
               gStringTable[loc.file_idx].c_str());
      snprintf(func_buf, sizeof(func_buf), "%s",
               gStringTable[loc.func_idx].c_str());
      line = loc.line;
    }
    gLock.unlock();
  }

  // Format the output according to libFuzzer's format specifiers.
  size_t pos = 0;
  // Bytes available for content (reserves one byte for the null terminator).
  auto remaining = [&]() -> size_t {
    return out_buf_size > pos + 1 ? out_buf_size - pos - 1 : 0;
  };
  auto advance = [&](int n) {
    if (n > 0) pos += std::min(static_cast<size_t>(n), remaining());
  };

  for (const char *f = fmt; *f && remaining() > 0; ++f) {
    if (*f == '%' && *(f + 1)) {
      ++f;
      switch (*f) {
        case 'p':
          // Virtual PCs are meaningless; eat the trailing space.
          if (*(f + 1) == ' ') ++f;
          break;
        case 'F':
          advance(snprintf(out_buf + pos, remaining() + 1, "in %s", func_buf));
          break;
        case 'L':
          advance(snprintf(out_buf + pos, remaining() + 1, "%s:%u", file_buf,
                           line));
          break;
        case 's':
          advance(snprintf(out_buf + pos, remaining() + 1, "%s", file_buf));
          break;
        case 'l':
          advance(snprintf(out_buf + pos, remaining() + 1, "%u", line));
          break;
        case 'c':
          // No column info from JVM bytecode; output 0.
          advance(snprintf(out_buf + pos, remaining() + 1, "0"));
          break;
        default:
          if (remaining() >= 2) {
            out_buf[pos++] = '%';
            out_buf[pos++] = *f;
          }
          break;
      }
    } else {
      out_buf[pos++] = *f;
    }
  }
  out_buf[pos] = '\0';
}

}  // namespace jazzer
