name: Check formatting

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

  workflow_dispatch:

jobs:
  check_formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install formatters
        run: |
          go install github.com/google/addlicense@latest

      - name: Run format.sh and print changes
        env:
          CI: 1
        run: |
          ./format.sh
          git diff

      - name: Check for changes
        run: "[ $(git status --porcelain | wc -l) -eq 0 ]"
