name: Check formatting

# Controls when the action will run.
on:
  pull_request:
    branches: [ main ]
  merge_group:

  workflow_dispatch:

jobs:
  check_formatting:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run format.sh and print changes
        env:
          CI: 1
        run: |
          ./format.sh
          git diff

      - name: Check for changes
        run: "[ $(git status --porcelain | wc -l) -eq 0 ]"
